# Generated by Django 4.0.5 on 2022-09-07 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=1000)),
                ('completion_date', models.DateField(default=datetime.datetime(2022, 9, 7, 10, 50, 33, 659999, tzinfo=utc))),
            ],
        ),
    ]
